name: Run Local Script on Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  test-local-script:
    runs-on: self-hosted
    steps:
      - name: Run a local Shell script
        run: bash ./regression.sh
