name: Run Batch Script on Windows Self-hosted Runner

on:
  push:
    branches:
      - main

jobs:
  run-batch-file:
    runs-on: self-hosted # Ensure you are using a self-hosted Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Batch Script
        run: ./regression.bat
